// O'zbekiston banklari MFO → Bank nomi ro'yxati
export const MFO_BANKS: Record<string, string> = {
  '00001': 'Markaziy bankning Banklararo hisob-kitoblar markazi',
  '00002': 'Markaziy bankning Chakana to\'lovlar kliring markazi',
  '00003': 'Markaziy bankning Tezkor to\'lovlar kliring markazi',
  '00014': 'Markaziy bank Toshkent shahar hisob-kitob kassa markazi',
  '00015': 'Markaziy bank Qoraqalpog\'iston Respublikasi hisob-kitob kassa markazi',
  '00016': 'Markaziy bank Andijon viloyati hisob-kitob kassa markazi',
  '00017': 'Markaziy bank Buxoro viloyati hisob-kitob kassa markazi',
  '00018': 'Markaziy bank Jizzax viloyati hisob-kitob kassa markazi',
  '00019': 'Markaziy bank Qashqadaryo viloyati hisob-kitob kassa markazi',
  '00020': 'Markaziy bank Navoiy viloyati hisob-kitob kassa markazi',
  '00021': 'Markaziy bank Namangan viloyati hisob-kitob kassa markazi',
  '00022': 'Markaziy bank Samarqand viloyati hisob-kitob kassa markazi',
  '00023': 'Markaziy bank Sirdaryo viloyati hisob-kitob kassa markazi',
  '00024': 'Markaziy bank Surxondaryo viloyati hisob-kitob kassa markazi',
  '00025': 'Markaziy bank Toshkent viloyati hisob-kitob kassa markazi',
  '00026': 'Markaziy bank Farg\'ona viloyati hisob-kitob kassa markazi',
  '00027': 'Markaziy bank Xorazm viloyati hisob-kitob kassa markazi',
  '00031': '"Agrobank" ATB Paxtaobod filiali',
  '00033': '"Agrobank" ATB Asaka filiali',
  '00035': '"Agrobank" ATB Marxamat filiali',
  '00037': '"Agrobank" ATB Shaxrixon filiali',
  '00040': '"Agrobank" ATB Jalaquduq filiali',
  '00042': '"Agrobank" ATB Xo\'jaobod filiali',
  '00045': '"Agrobank" ATB Izboskan filiali',
  '00049': '"Agrobank" ATB Oltinko\'l filiali',
  '00053': '"Agrobank" ATB Bo\'ston filiali',
  '00055': '"Agrobank" ATB Ulug\'nor filiali',
  '00056': '"Agrobank" ATB Qo\'rg\'ontepa filiali',
  '00059': '"Ipoteka-bank" ATIB Andijon viloyat filiali',
  '00062': '"Agrobank" ATB Andijon filiali',
  '00064': '"Agrobank" ATB Buloqboshi filiali',
  '00066': '"Agrobank" ATB Baliqchi filiali',
  '00068': '"Ipoteka-bank" ATIB Istiklol filiali',
  '00069': '"Asakabank" AJ Andijon filiali',
  '00073': '"Asakabank" AJ Bobur filiali',
  '00074': '"O\'zmilliybank" Andijon bo\'limi',
  '00077': '"Agrobank" ATB Andijon viloyat hududiy boshqarmasi',
  '00083': 'Chet el kapitali ishtirokidagi "Hamkorbank" ATB bosh ofisi',
  '00088': '"Ipoteka-bank" ATIB Buxoro viloyat filiali',
  '00089': '"Agrobank" ATB Buxoro viloyat hududiy boshqarmasi',
  '00090': '"Agrobank" ATB Olot filiali',
  '00091': '"Agrobank" ATB Vobkent filiali',
  '00092': '"Agrobank" ATB G\'ijduvon filiali',
  '00093': '"Agrobank" ATB Shofirkon filiali',
  '00094': '"Agrobank" ATB Qorako\'l filiali',
  '00095': '"Agrobank" ATB Romitan filiali',
  '00096': '"Agrobank" ATB Jondor filiali',
  '00097': '"Agrobank" ATB Buxoro filiali',
  '00098': '"Agrobank" ATB Peshku filiali',
  '00119': '"Ipoteka-bank" ATIB "Sardor" filiali',
  '00120': '"Asakabank" AJ Buxoro filiali',
  '00121': '"O\'zmilliybank" Jizzax bo\'limi',
  '00122': '"Ipoteka-bank" ATIB Jizzax viloyat filiali',
  '00123': '"Agrobank" ATB Jizzax filiali',
  '00124': '"Agrobank" ATB Arnasoy filiali',
  '00125': '"Agrobank" ATB Zarbdor filiali',
  '00126': '"Agrobank" ATB Jizzax viloyat hududiy filiali',
  '00127': '"Agrobank" ATB Paxtakor filiali',
  '00128': '"Agrobank" ATB G\'allaorol filiali',
  '00129': '"Agrobank" ATB Do\'stlik filiali',
  '00130': '"Agrobank" ATB Mirzacho\'l filiali',
  '00131': '"Agrobank" ATB Zomin filiali',
  '00132': '"Agrobank" ATB Baxmal filiali',
  '00133': '"Agrobank" ATB Forish filiali',
  '00134': '"Agrobank" ATB Zafarobod filiali',
  '00140': '"Asakabank" AJ Jizzax filiali',
  '00151': '"Agrobank" ATB Qashqadaryo viloyat hududiy filiali',
  '00157': '"Agrobank" ATB G\'uzor filiali',
  '00158': '"Agrobank" ATB Dehqonobod filiali',
  '00160': '"Agrobank" ATB Qamashi filiali',
  '00162': '"Agrobank" ATB Koson filiali',
  '00165': '"Ipoteka-bank" ATIB Shahrisabz filiali',
  '00166': '"Agrobank" ATB Shahrisabz filiali',
  '00169': '"Agrobank" ATB Yakkabog\' filiali',
  '00172': '"Agrobank" ATB Qarshi filiali',
  '00174': '"Agrobank" ATB Chiroqchi filiali',
  '00176': '"Agrobank" ATB Kitob filiali',
  '00179': '"Agrobank" ATB Kasbi filiali',
  '00181': '"Agrobank" ATB Nishon filiali',
  '00184': '"Agrobank" ATB Mirishkor filiali',
  '00187': '"Agrobank" ATB Muborak filiali',
  '00190': '"Ipoteka-bank" ATIB Qashqadaryo viloyat filiali',
  '00194': '"Asakabank" AJ Qarshi filiali',
  '00197': '"Agrobank" ATB Navoiy viloyat hududiy filiali',
  '00199': '"Ipak Yo\'li" AIT banki Navoiy filiali',
  '00201': 'AJ "Garant bank" Navoiy shahar filiali',
  '00203': '"Ipoteka-bank" ATIB Zarafshon filiali',
  '00205': '"Ipoteka-bank" ATIB Navoiy filiali',
  '00206': '"Asakabank" AJ Navoiy filiali',
  '00209': '"Agrobank" ATB Konimex filiali',
  '00210': '"Agrobank" ATB Karmana filiali',
  '00212': '"Agrobank" ATB Qiziltepa filiali',
  '00214': '"Agrobank" ATB Nurota filiali',
  '00216': '"Agrobank" ATB Tomdi filiali',
  '00217': '"Agrobank" ATB Navbaxor filiali',
  '00219': '"Agrobank" ATB Xatirchi filiali',
  '00222': '"O\'zmilliybank" Namangan bo\'limi',
  '00223': '"Ipoteka-bank" ATIB Namangan viloyat filiali',
  '00225': '"Agrobank" ATB Namangan viloyat hududiy filiali',
  '00227': 'AJ "Garant bank" Namangan shahar filiali',
  '00231': '"Asakabank" AJ Namangan filiali',
  '00232': '"Agrobank" ATB Mingbuloq filiali',
  '00234': '"Agrobank" ATB Kosonsoy filiali',
  '00236': '"Agrobank" ATB Norin filiali',
  '00238': '"Agrobank" ATB Pop filiali',
  '00241': '"Agrobank" ATB To\'raqo\'rg\'on filiali',
  '00244': '"Agrobank" ATB Uychi filiali',
  '00246': '"Agrobank" ATB Uchqo\'rg\'on filiali',
  '00249': '"Agrobank" ATB Chust filiali',
  '00251': '"Agrobank" ATB Yangiqo\'rg\'on filiali',
  '00253': '"Agrobank" ATB Namangan filiali',
  '00256': '"Agrobank" ATB Chortoq filiali',
  '00259': '"Agrobank" ATB Davlatobod filiali',
  '00262': '"Ipoteka-bank" ATIB Ko\'ksaroy filiali',
  '00264': '"Asakabank" AJ Samarqand filiali',
  '00265': '"Agrobank" ATB Oqdaryo filiali',
  '00267': '"Agrobank" ATB Narpay filiali',
  '00270': '"Agrobank" ATB Jomboy filiali',
  '00273': '"Agrobank" ATB Pastdarg\'om filiali',
  '00275': '"Agrobank" ATB Kattaqo\'rg\'on filiali',
  '00278': '"O\'zmilliybank" Samarqand bo\'limi',
  '00279': '"Agrobank" ATB Samarqand viloyat hududiy filiali',
  '00280': '"Agrobank" ATB Siyob filiali',
  '00283': '"Ipak Yo\'li" AIT banki Umar mintaqaviy filiali',
  '00290': '"Agrobank" ATB Bulung\'ur filiali',
  '00291': '"Agrobank" ATB Nurobod filiali',
  '00297': '"Agrobank" ATB Paxtachi filiali',
  '00300': '"Agrobank" ATB Urgut filiali',
  '00307': '"Agrobank" ATB Go\'zalkent filiali',
  '00309': '"Agrobank" ATB Ishtixon filiali',
  '00312': '"Ipoteka-bank" ATIB Samarqand viloyat filiali',
  '00313': '"Agrobank" ATB Qo\'shrabod filiali',
  '00318': '"Agrobank" ATB Payariq filiali',
  '00321': '"Agrobank" ATB Toyloq filiali',
  '00325': '"Agrobank" ATB Surxondaryo viloyat hududiy filiali',
  '00331': '"Agrobank" ATB Boysun filiali',
  '00332': '"Agrobank" ATB Jarqo\'rg\'on filiali',
  '00334': '"Agrobank" ATB Muzrabod filiali',
  '00337': '"Agrobank" ATB Sherobod filiali',
  '00339': '"Agrobank" ATB Sho\'rchi filiali',
  '00341': '"Agrobank" ATB Uzun filiali',
  '00343': '"Agrobank" ATB Angor filiali',
  '00345': '"Agrobank" ATB Qiziriq filiali',
  '00347': '"Agrobank" ATB Qumqo\'rg\'on filiali',
  '00349': '"Agrobank" ATB Termiz filiali',
  '00351': '"Agrobank" ATB Oltinsoy filiali',
  '00355': '"Agrobank" ATB Sariosiyo filiali',
  '00356': '"Ipoteka-bank" ATIB Surxondaryo viloyat filiali',
  '00358': '"Asakabank" AJ Termiz filiali',
  '00360': '"Agrobank" ATB Denov filiali',
  '00363': '"O\'zmilliybank" Sirdaryo bo\'limi',
  '00364': '"Ipoteka-bank" ATIB Sirdaryo viloyat filiali',
  '00365': '"Agrobank" ATB Sirdaryo viloyat hududiy filiali',
  '00373': '"Asakabank" AJ Guliston filiali',
  '00374': '"Agrobank" ATB Sardoba filiali',
  '00375': '"Agrobank" ATB Sirdaryo filiali',
  '00378': '"Agrobank" ATB Yangiyer filiali',
  '00382': '"Agrobank" ATB Boyovut filiali',
  '00383': '"Agrobank" ATB Shirin filiali',
  '00386': '"Agrobank" ATB Guliston filiali',
  '00388': '"Agrobank" ATB Sayxunobod filiali',
  '00390': '"Agrobank" ATB Oqoltin filiali',
  '00392': '"Agrobank" ATB Xovos filiali',
  '00394': '"Agrobank" ATB Toshkent shahar filiali',
  '00395': '"Ziraat Bank Uzbekistan" AJ',
  '00401': 'AT "Aloqabank" bosh ofisi',
  '00408': '"Ipoteka-bank" ATIB Toshkent viloyat filiali',
  '00411': '"Asakabank" AJ Nurafshon filiali',
  '00413': '"Agrobank" ATB Ohangaron filiali',
  '00416': '"Asakabank" AJ Poytaxt filiali',
  '00417': '"Asakabank" AJ Avtotransport filiali',
  '00419': '"Ipoteka-bank" ATIB Toshkent shahar filiali',
  '00420': '"Ipoteka-bank" ATIB Mirobod filiali',
  '00421': '"Ipak Yo\'li" AIT banki Mirzo Ulug\'bek filiali',
  '00423': '"Ipoteka-bank" ATIB Mexnat filiali',
  '00425': '"Ipoteka-bank" ATIB Shayxontoxur filiali',
  '00433': '"Mikrokreditbank" ATB bosh ofisi',
  '00439': 'AJ "Garant bank" bosh ofisi',
  '00440': '"O\'zsanoatqurilishbank" ATB bosh ofisi',
  '00444': '"Ipak Yo\'li" AIT banki bosh ofisi',
  '00445': '"Kapitalbank" ATB Toshkent shahar filiali',
  '00446': '"Turonbank" ATB bosh ofisi',
  '00450': '"O\'zmilliybank" bosh ofisi',
  '00454': '"Agrobank" ATB Shayxontohur filiali',
  '00457': '"Agrobank" ATB Oqqo\'rg\'on filiali',
  '00459': '"Ipoteka-bank" ATIB Olmaliq filiali',
  '00461': '"Ipoteka-bank" ATIB Angren filiali',
  '00463': '"Agrobank" ATB Bo\'ka filiali',
  '00468': '"Agrobank" ATB Bekobod filiali',
  '00472': '"Agrobank" ATB Pskent filiali',
  '00474': '"Agrobank" ATB Quyichirchiq filiali',
  '00475': '"Agrobank" ATB Toshkent viloyat hududiy filiali',
  '00476': '"Agrobank" ATB Chinoz filiali',
  '00478': '"Ipoteka-bank" ATIB Chirchiq filiali',
  '00480': '"Agrobank" ATB Yuqorichirchiq filiali',
  '00482': '"Agrobank" ATB Parkent filiali',
  '00485': '"Agrobank" ATB Yangiyo\'l filiali',
  '00487': '"Ipoteka-bank" ATIB Ohangaron filiali',
  '00489': '"Ipoteka-bank" ATIB Bekobod filiali',
  '00491': '"Trastbank" XAB bosh ofisi',
  '00493': '"O\'zmilliybank" Farg\'ona bo\'limi',
  '00495': '"Agrobank" ATB Farg\'ona viloyat hududiy filiali',
  '00502': '"Agrobank" ATB Oltiariq filiali',
  '00504': '"Agrobank" ATB Bog\'dod filiali',
  '00507': '"Agrobank" ATB Farg\'ona filiali',
  '00510': '"Agrobank" ATB Dang\'ara filiali',
  '00511': '"Agrobank" ATB Uchko\'prik filiali',
  '00513': '"Agrobank" ATB Beshariq filiali',
  '00515': '"Agrobank" ATB Qo\'shtepa filiali',
  '00517': '"Agrobank" ATB Quvasoy filiali',
  '00519': '"Agrobank" ATB Rishton filiali',
  '00522': '"Agrobank" ATB Toshloq filiali',
  '00525': '"Agrobank" ATB Buvayda filiali',
  '00528': '"Agrobank" ATB Marg\'ilon filiali',
  '00529': '"Agrobank" ATB Quva filiali',
  '00533': '"Agrobank" ATB O\'zbekiston filiali',
  '00539': '"Asakabank" AJ Farg\'ona filiali',
  '00541': '"Agrobank" ATB Yozyovon filiali',
  '00542': '"Agrobank" ATB So\'x filiali',
  '00544': '"Ipoteka-bank" ATIB Farg\'ona viloyat filiali',
  '00545': '"O\'zmilliybank" Qo\'qon filiali',
  '00546': '"Agrobank" ATB Qo\'qon filiali',
  '00548': '"Agrobank" ATB Xorazm viloyat hududiy filiali',
  '00554': '"Agrobank" ATB Gurlan filiali',
  '00556': '"Agrobank" ATB Bog\'ot filiali',
  '00558': '"Agrobank" ATB Xozorasp filiali',
  '00560': '"Agrobank" ATB Xonqa filiali',
  '00563': '"Agrobank" ATB Yangiariq filiali',
  '00565': '"Agrobank" ATB Qo\'shko\'pir filiali',
  '00567': '"Agrobank" ATB Shovot filiali',
  '00569': '"Agrobank" ATB Urganch filiali',
  '00574': '"Agrobank" ATB Yangibozor filiali',
  '00579': '"Ipoteka-bank" ATIB Xorazm viloyat filiali',
  '00580': '"Ipoteka-bank" ATIB "Tinchlik" filiali',
  '00581': '"Asakabank" AJ Urganch filiali',
  '00583': '"Agrobank" ATB Qoraqalpog\'iston hududiy filiali',
  '00589': '"Agrobank" ATB Kegeyli filiali',
  '00590': '"Agrobank" ATB Shumanay filiali',
  '00592': '"Agrobank" ATB Qo\'ng\'irot filiali',
  '00594': '"Agrobank" ATB Mo\'ynoq filiali',
  '00595': '"Agrobank" ATB Nukus filiali',
  '00597': '"Agrobank" ATB Taxtako\'pir filiali',
  '00598': '"Agrobank" ATB To\'rtko\'l filiali',
  '00602': '"Agrobank" ATB Xo\'jayli filiali',
  '00605': '"Agrobank" ATB Chimboy filiali',
  '00607': '"Agrobank" ATB Beruniy filiali',
  '00609': '"Agrobank" ATB Qonliko\'l filiali',
  '00612': '"Agrobank" ATB Qorauzak filiali',
  '00614': '"Agrobank" ATB Ellikqal\'a filiali',
  '00619': '"Agrobank" ATB Amudaryo filiali',
  '00621': '"Ipoteka-bank" ATIB Qoraqalpog\'iston Respublikasi filiali',
  '00625': '"Asakabank" AJ Nukus filiali',
  '00631': '"Asakabank" AJ Qo\'qon filiali',
  '00837': '"Ipoteka-bank" ATIB Yunusobod filiali',
  '00842': '"KDB Bank O\'zbekiston" AJ bosh ofisi',
  '00865': '"O\'zmilliybank" Urgut filiali',
  '00873': '"Asakabank" AJ bosh ofisi',
  '00877': '"O\'zmilliybank" Uychi filiali',
  '00881': '"O\'zmilliybank" Uchqo\'rg\'on filiali',
  '00885': '"O\'zmilliybank" Beshariq filiali',
  '00886': '"O\'zmilliybank" Quva filiali',
  '00892': '"O\'zmilliybank" Jizzax industrial filiali',
  '00893': '"O\'zmilliybank" Asaka filiali',
  '00901': '"Ipoteka-bank" ATIB Olmazor filiali',
  '00913': '"O\'zmilliybank" Jomboy filiali',
  '00916': '"O\'zmilliybank" Mirzacho\'l filiali',
  '00929': '"Agrobank" ATB Samarqand filiali',
  '00932': '"O\'zmilliybank" Chortoq filiali',
  '00937': '"Ipoteka-bank" ATIB bosh ofisi',
  '00941': '"O\'zmilliybank" Pastdarg\'om filiali',
  '00946': '"O\'zmilliybank" Rishton filiali',
  '00950': 'Eron "Soderot" bankining O\'zbekiston Respublikasi Toshkent shahridagi sho\'ba banki',
  '00955': '"O\'zmilliybank" Marxamat filiali',
  '00958': '"Asakabank" AJ Sergeli filiali',
  '00959': '"Ipoteka-bank" ATIB Yashnobod filiali',
  '00963': '"Asakabank" AJ Yunusobod filiali',
  '00969': '"Asakabank" AJ Shayxontohur filiali',
  '00973': 'ATB "Universal bank" bosh ofisi',
  '00974': '"Kapitalbank" ATB Amaliyotlar boshqarmasi',
  '00978': '"Ipoteka-bank" ATIB Sirg\'ali filiali',
  '00980': '"OCTOBANK" Aksiyadorlik jamiyati',
  '00981': '"DAVR BANK" XATB bosh ofisi',
  '00997': '"Ipoteka-bank" ATIB Chilonzor filiali',
  '00999': '"Ipak Yo\'li" AIT banki O\'rikzor filiali',
  '01017': '"Ipoteka-bank" ATIB Yakkasaroy filiali',
  '01018': '"Kapitalbank" ATB Mirzo-Ulug\'bek filiali',
  '01021': '"Asakabank" AJ Zarafshon filiali',
  '01028': '"Ipak Yo\'li" AIT banki Yakkasaroy filiali',
  '01032': '"Kapitalbank" ATB Termiz filiali',
  '01033': '"Kapitalbank" ATB Chorsu filiali',
  '01036': '"Ipak Yo\'li" AIT banki Sag\'bon filiali',
  '01037': 'ATB "Biznesni rivojlantirish banki"',
  '01038': '"Kapitalbank" ATB Nukus filiali',
  '01039': '"Ipoteka-bank" ATIB Chinoz filiali',
  '01041': '"InFinBank" AJ bosh ofisi',
  '01042': '"Kapitalbank" ATB Sirg\'ali filiali',
  '01043': '"Kapitalbank" ATB Farg\'ona filiali',
  '01046': '"DAVR BANK" XATB Chilonzor filiali',
  '01048': '"Ipak Yo\'li" AIT banki Shahrisabz filiali',
  '01054': '"Ipak Yo\'li" AIT banki Namangan filiali',
  '01056': '"InFinBank" AJ Toshkent viloyat filiali',
  '01061': '"Kapitalbank" ATB Samarqand filiali',
  '01065': '"KDB Bank O\'zbekiston" AJ Oybek filiali',
  '01067': '"Ipak Yo\'li" AIT banki Chilonzor filiali',
  '01069': '"DAVR BANK" XATB Yakkasaroy filiali',
  '01070': '"InFinBank" AJ Sirg\'ali filiali',
  '01071': '"Orient Finans" XATB bosh ofisi',
  '01072': '"DAVR BANK" XATB Mirzo Ulug\'bek filiali',
  '01076': '"Ipoteka-bank" ATIB Qo\'qon filiali',
  '01080': '"InFinBank" AJ Zangiota filiali',
  '01081': '"Ipak Yo\'li" AIT banki Yangiyo\'l filiali',
  '01082': '"Kapitalbank" ATB Buxoro filiali',
  '01085': '"Kapitalbank" ATB Namangan filiali',
  '01086': '"DAVR BANK" XATB Uchtepa filiali',
  '01087': '"Kapitalbank" ATB Qo\'qon filiali',
  '01088': '"Kapitalbank" ATB bosh ofisi',
  '01095': '"ASIA ALLIANCE BANK" ATB bosh ofisi',
  '01101': '"Ipak Yo\'li" AIT banki Mirobod filiali',
  '01107': '"InFinBank" AJ Buxoro viloyat filiali',
  '01112': '"O\'zmilliybank" Registon filiali',
  '01113': '"InFinBank" AJ Namangan viloyat filiali',
  '01114': '"InFinBank" AJ Andijon viloyat filiali',
  '01116': '"InFinBank" AJ Qo\'qon filiali',
  '01119': '"Ipak Yo\'li" AIT banki Qarshi filiali',
  '01120': '"Ipak Yo\'li" AIT banki Andijon filiali',
  '01121': '"DAVR BANK" XATB Olmazor filiali',
  '01122': '"DAVR BANK" XATB Yunusobod filiali',
  '01125': 'AT Xalq banki Bosh amaliyotlar boshqarmasi',
  '01128': '"InFinBank" AJ Farg\'ona viloyat filiali',
  '01129': '"InFinBank" AJ Xorazm viloyat filiali',
  '01130': '"Ipoteka-bank" ATIB Zangiota filiali',
  '01133': '"InFinBank" AJ Samarqand viloyat filiali',
  '01135': '"InFinBank" AJ Qashqadaryo viloyat filiali',
  '01136': '"Kapitalbank" ATB Yashnabod filiali',
  '01139': '"InFinBank" AJ Qoraqalpog\'iston filiali',
  '01140': '"Agrobank" ATB Markaziy amaliyotlar boshqarmasi',
  '01142': '"Madad Invest Bank" ATB',
  '01145': '"Ipak Yo\'li" AIT banki Shayxontohur filiali',
  '01148': '"InFinBank" AJ Navoiy viloyati filiali',
  '01150': '"AVO BANK" aksiyadorlik jamiyati',
  '01158': '"Kapitalbank" AT bankining amaliyot filiali',
  '01165': '"InFinBank" AJ Uchtepa filiali',
  '01168': '"Ipak Yo\'li" AIT banki Farg\'ona filiali',
  '01170': '"Ipoteka-bank" ATIB Do\'stobod filiali',
  '01172': '"POYTAXT BANK" bosh ofisi',
  '01176': '"Tenge Bank" ATB bosh ofisi',
  '01180': '"TBC Bank" ATB bosh ofisi',
  '01183': '"ANOR BANK" AJ bosh ofisi',
  '01184': '"Kapitalbank" ATB Toshkent shahar raqamli filiali',
  '01186': 'ATB "Universal bank" Mirobod raqamli filiali',
  '01188': '"Ipak Yo\'li" AIT banki Buxoro filiali',
  '01190': '"UZUM BANK" Aksiyadorlik jamiyati',
  '01194': '"Agrobank" ATB "FRESH" filiali',
  '01196': '"APEX BANK" Aksiyadorlik jamiyati',
  '01197': '"YANGI BANK" Aksiyadorlik jamiyati',
  '01198': '"HAYOT BANK" aksiyadorlik jamiyati',
  '01199': '"SMART BANK" Aksiyadorlik jamiyati',
  '01204': '"Yevroosiyo Banki" aksiyadorlik jamiyati',
  '09001': 'Markaziy bankning to\'lov markazi',
  '09002': '"O\'zmilliybank" Hisob-kitob kliring markazi',
  '09003': '"O\'zsanoatqurilishbank" ATB to\'lov markazi',
  '09004': '"Agrobank" ATB hisob-kitob markazi',
  '09005': '"Mikrokreditbank" ATB axborotlarni hisoblash markazi',
  '09008': 'AJ "Garant bank" to\'lov markazi',
  '09013': '"Asakabank" AJ to\'lov markazi',
  '09014': '"Ipak Yo\'li" AIT banki hisob-kitob markazi',
  '09020': '"Ziraat Bank Uzbekistan" AJ To\'lov markazi',
  '09030': '"Trastbank" XAB to\'lov markazi',
  '09033': '"Ipoteka-bank" ATIB to\'lov markazi',
  '09034': '"KDB Bank O\'zbekiston" AJ to\'lov markazi',
  '09048': 'ATB "Universal bank" to\'lov markazi',
  '09049': '"Kapitalbank" ATB hisob-kitob markazi',
  '09051': '"DAVR BANK" XATB to\'lov markazi',
  '09053': '"InFinBank" AJ to\'lov markazi',
  '09055': '"ASIA ALLIANCE BANK" ATB to\'lov markazi',
  '09057': '"Orient Finans" XATB to\'lov markazi',
}

export function getBankByMfo(mfo: string): string | null {
  return MFO_BANKS[mfo.padStart(5, '0')] || null
}
